(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['case'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <link rel=\"stylesheet\" href=\"style/nav.css\">\n    <link rel=\"stylesheet\" href=\"style/footer.css\">\n    <link rel=\"stylesheet\" href=\"style/case.css\">\n    <title>Document</title>\n</head>\n<body>\n    <section class=\"home_0\"></section>\n\n    <section class=\"bodyCase\">\n        <article class=\"textCase\">"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"texto") || (depth0 != null ? lookupProperty(depth0,"texto") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"texto","hash":{},"data":data,"loc":{"start":{"line":14,"column":34},"end":{"line":14,"column":45}}}) : helper))) != null ? stack1 : "")
    + "</article>\n        <div class=\"img\">\n            "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"img1") || (depth0 != null ? lookupProperty(depth0,"img1") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"img1","hash":{},"data":data,"loc":{"start":{"line":16,"column":12},"end":{"line":16,"column":22}}}) : helper))) != null ? stack1 : "")
    + "\n            "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"img2") || (depth0 != null ? lookupProperty(depth0,"img2") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"img2","hash":{},"data":data,"loc":{"start":{"line":17,"column":12},"end":{"line":17,"column":22}}}) : helper))) != null ? stack1 : "")
    + "\n        </div>\n    </section>\n    <section class=\"infoNext\">\n        <div class=\"infoCase\">\n            <article>\n                <p class=\"bold\">Cliente</p>\n                <a>"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"nextProyect") || (depth0 != null ? lookupProperty(depth0,"nextProyect") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"nextProyect","hash":{},"data":data,"loc":{"start":{"line":24,"column":19},"end":{"line":24,"column":36}}}) : helper))) != null ? stack1 : "")
    + "</a>\n            </article>\n            <article>\n                <p class=\"bold\">Sector</p>\n                <a>"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"sectorProyect") || (depth0 != null ? lookupProperty(depth0,"sectorProyect") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"sectorProyect","hash":{},"data":data,"loc":{"start":{"line":28,"column":19},"end":{"line":28,"column":38}}}) : helper))) != null ? stack1 : "")
    + "</a>\n            </article>\n        </div>\n        <div class=\"logoContainer\">\n            <div class=\"logo\">"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"logoProyect") || (depth0 != null ? lookupProperty(depth0,"logoProyect") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"logoProyect","hash":{},"data":data,"loc":{"start":{"line":32,"column":30},"end":{"line":32,"column":47}}}) : helper))) != null ? stack1 : "")
    + "</div>\n            <div class=\"nextCase\">\n                <p>Siguiente Proyecto</p>\n                <svg width=\"90\" height=\"55\" viewBox=\"0 0 90 55\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n                    <path d=\"M62.5821 0L59.8324 2.75551L82.3638 25.335H0V29.2399H82.7252L59.7853 52.2445L62.5349 55L90 27.4764L62.5821 0Z\" fill=\"#4538DA\"/>\n                </svg>\n            </div>\n        </div>\n    </section>\n</body>\n</html>";
},"useData":true});
templates['footer'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "    <div class=\"footer\">\n        <div class=\"container_1\">\n            <div class=\"subtitle\"><span>W - World</span>Consulting.</div>\n            <h3 class=\"text-footer\">Wanna build something great together?<br>Let's talk</h3>\n        </div>\n        <div class=\"container_2\">\n            <form action=\"\" class=\"formulario\">\n                <div class=\"input_container\">\n                    <input type=\"text\" name=\"nombre\" id=\"nombre\" placeholder=\"Nombre y Apellido\">\n                    <input type=\"email\" name=\"email\" id=\"email\" placeholder=\"Correo Electronico\">\n                </div>\n                <textarea name=\"\" id=\"\" cols=\"30\" placeholder=\"Mensaje\"></textarea>\n            </form>\n        </div>\n        <div class=\"redes-footer\">\n            <img src=\"img/footer_persona.png\" alt=\"\" class=\"logo\" />\n            <div class=\"redes\">\n                <a>walter@wwclatam.com</a>\n                <a>Instagram</a>\n                <a>Linkedin</a>\n            </div>\n        </div>\n    </div>";
},"useData":true});
templates['nav'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "        <div class=\"redes_container\">\n            <div><img/></div>\n            <nav id=\"redes\" class=\"redes\">\n                <a class=\"ig\" id=\"ig\">instagram</a>\n                <a class=\"ld\" id=\"ld\">linkedin</a>\n                <select name=\"\" id=\"language\" class=\"language\">\n                    <option value=\"eng\">English</option>\n                    <option value=\"esp\">Español</option>\n                </select>\n            </nav>\n        </div>\n\n        <div class=\"main_container\">\n            <h6 class=\"subtitle\">W - World<span class=\"bold\">Consulting.</span></h6>\n            <nav class=\"main_nav\" id=\"main_nav\">\n                <a class=\"home\" id=\"home\">Home</a>\n                <a class=\"mision\" id=\"mision\">Mision</a>\n                <a class=\"approach\" id=\"approach\">Approach\n                    <a class=\"team\" id=\"team\">Team</a>\n                    <a class=\"cases\" id=\"cases\">Cases</a>\n            </nav>\n        </div>";
},"useData":true});
templates['paso'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"paso\">\n    <header>\n        <div class=\"number\">\n            01\n        </div>\n        <div class=\"text\">\n            <span class=\"titulo\">Encuentra el problema</span>\n            <p>¿Qué problema se resuelve primero? No importa.\n                Con tiempo y energía, se arregla el que más repercusión tenga\n                en el balance final.</p>\n        </div>\n    </header>\n    <div class=\"lista\">\n        <div>Marketing Research</div>\n        <div>Escucha a tu Equipo</div>\n        <div>Analizar el Problema</div>\n    </div>\n</div>";
},"useData":true});
templates['titleCase'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "    <section class=\"titleContainer\">\n        <h2 class=\"title\">\n            <div>\n                <p>"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"optionalLine") || (depth0 != null ? lookupProperty(depth0,"optionalLine") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"optionalLine","hash":{},"data":data,"loc":{"start":{"line":4,"column":19},"end":{"line":4,"column":37}}}) : helper))) != null ? stack1 : "")
    + "</p>\n            </div>\n            <div>\n                <p>"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"needLine") || (depth0 != null ? lookupProperty(depth0,"needLine") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"needLine","hash":{},"data":data,"loc":{"start":{"line":7,"column":19},"end":{"line":7,"column":33}}}) : helper))) != null ? stack1 : "")
    + "</p> \n                <span class=\"flecha\">\n                    <svg width=\"90\" height=\"55\" viewBox=\"0 0 90 55\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n                        <path d=\"M62.5821 0L59.8324 2.75551L82.3638 25.335H0V29.2399H82.7252L59.7853 52.2445L62.5349 55L90 27.4764L62.5821 0Z\" fill=\"white\"/>\n                    </svg>                        \n                </span>\n            </div>\n        </h2>\n    </section>";
},"useData":true});
templates['footer.js'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "!function(){var a=Handlebars.template;(Handlebars.templates=Handlebars.templates||{}).footer=a({compiler:[8,\">= 4.3.0\"],main:function(a,e,n,t,i){return'    <div class=\"footer\">\\n        <div class=\"container_1\">\\n            <div class=\"subtitle\"><span>W - World</span>Consulting.</div>\\n            <h3 class=\"text-footer\">Wanna build something great together?<br>Let\\'s talk</h3>\\n        </div>\\n        <div class=\"container_2\">\\n            <form action=\"\" class=\"formulario\">\\n                <div class=\"input_container\">\\n                    <input type=\"text\" name=\"nombre\" id=\"nombre\" placeholder=\"Nombre y Apellido\">\\n                    <input type=\"email\" name=\"email\" id=\"email\" placeholder=\"Correo Electronico\">\\n                </div>\\n                <textarea name=\"\" id=\"\" cols=\"30\" placeholder=\"Mensaje\"></textarea>\\n            </form>\\n        </div>\\n        <div class=\"redes-footer\">\\n            <img src=\"img/footer_persona.png\" alt=\"\" class=\"logo\" />\\n            <div class=\"redes\">\\n                <a>walter@wwclatam.com</a>\\n                <a>Instagram</a>\\n                <a>Linkedin</a>\\n            </div>\\n        </div>\\n    </div>'},useData:!0})}();\n";
},"useData":true});
templates['nav.js'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "!function(){var a=Handlebars.template;(Handlebars.templates=Handlebars.templates||{}).nav=a({compiler:[8,\">= 4.3.0\"],main:function(a,n,s,i,e){return'        <div class=\"redes_container\">\\n            <div><img src=\"img/cuotesNav.png\"></div>\\n            <nav id=\"redes\" class=\"redes\">\\n                <a class=\"ig\" id=\"ig\">instagram</a>\\n                <a class=\"ld\" id=\"ld\">linkedin</a>\\n                <select name=\"\" id=\"language\" class=\"language\">\\n                    <option value=\"eng\">English</option>\\n                    <option value=\"esp\">Español</option>\\n                </select>\\n            </nav>\\n        </div>\\n\\n        <div class=\"main_container\">\\n            <h6 class=\"subtitle\">W - World<span class=\"bold\">Consulting.</span></h6>\\n            <nav class=\"main_nav\" id=\"main_nav\">\\n                <a class=\"home\" id=\"home\">Home</a>\\n                <a class=\"mision\" id=\"mision\">Mision</a>\\n                <a class=\"approach\" id=\"approach\">Approach\\n                    <a class=\"team\" id=\"team\">Team</a>\\n                    <a class=\"cases\" id=\"cases\">Cases</a>\\n            </nav>\\n        </div>'},useData:!0})}();\n";
},"useData":true});
templates['titleCase.js'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    return "!function(){var n=Handlebars.template;(Handlebars.templates=Handlebars.templates||{}).titleCase=n({compiler:[8,\">= 4.3.0\"],main:function(n,l,e,t,a){var i,o=null!=l?l:n.nullContext||{},s=n.hooks.helperMissing,p=\"function\",c=n.lookupProperty||function(n,l){if(Object.prototype.hasOwnProperty.call(n,l))return n[l]};return'    <section class=\"titleContainer\">\\n        <h2 class=\"title\">\\n            <div>\\n                <p>'+(null!=(n=typeof(i=null!=(i=c(e,\"optionalLine\")||(null!=l?c(l,\"optionalLine\"):l))?i:s)==p?i.call(o,{name:\"optionalLine\",hash:{},data:a,loc:{start:{line:4,column:19},end:{line:4,column:37}}}):i)?n:\"\")+\"</p>\\n            </div>\\n            <div>\\n                <p>\"+(null!=(n=typeof(i=null!=(i=c(e,\"needLine\")||(null!=l?c(l,\"needLine\"):l))?i:s)==p?i.call(o,{name:\"needLine\",hash:{},data:a,loc:{start:{line:7,column:19},end:{line:7,column:33}}}):i)?n:\"\")+'</p> \\n                <span class=\"flecha\">\\n                    <svg width=\"90\" height=\"55\" viewBox=\"0 0 90 55\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\\n                        <path d=\"M62.5821 0L59.8324 2.75551L82.3638 25.335H0V29.2399H82.7252L59.7853 52.2445L62.5349 55L90 27.4764L62.5821 0Z\" fill=\"white\"/>\\n                    </svg>                        \\n                </span>\\n            </div>\\n        </h2>\\n    </section>'},useData:!0})}();\n";
},"useData":true});
})();